### ISSUE TITLE
library imports after installation

### ISSUE THREAD

**Issue by pr4deepr** [BackmanLab/PWSpy#17]
Hi 
  I was trying out your example notebook after installing pwspy using conda. 
I got an this error:
`ModuleNotFoundError: No module named 'mpl_qt_viz'
`
Looks like it was not installed as part of PWSpy. 

Also, to run the example notebooks, it looks like you have to clone the repo and run it from the repo folder, especially for this import:
`from examples import PWSImagePath
`
I think it would be nice if the examples could be included as part of the package or perhaps downloaded if required. 

Cheers
Pradeep

**Comment by nanthony21** [comment]
Hi Pradeep,

I can see how this could be confusing. On the one hand I wouldn't want to add new dependencies to PWSpy just for the sole purpose of having the examples be easier to run and on the other hand I wouldn't want to limit the examples to only use dependencies that are already included with PWSpy. Do you think that maybe a suitable solution would be to go through the examples and add comments that clearly indicate where additional dependencies are needed along with instructions on where to get them?

The examples exist primarily for the purpose of appearing in the [documentation](https://pwspy.readthedocs.io/en/dev/examples.html) but you are right that it also shouldn't be overly difficult to run them. I looked at a few popular Python libraries like Numpy, Matplotlib, and Pandas and none of them include the examples as part of the distribution, just as a part of the documentation. I think this makes sense. The examples are meant to demonstrate the code so if they are also a part of the code it creates kind of a weird circular organization of the code. 

The issue I ran into is that unlike many other libraries PWSpy requires some test data in order to perform any meaningful example. Rather than have each example have a variable pointing to the location of test data that a user of the example would need to set I created a single variable (examples.PWSImagePath). That way the user could just set that variable and all of the examples would work. However, what I now realize is that in order for that the work the user must have their working directory set properly and must also have the `examples/__init__.py` file which is just making things even more complicated.

How about if I just go back to where each example has it's own `PWSImagePath` with a `# TODO` directing the example user to set the variable to the correct path for their system? That way it will be possible to run the examples just like you would for any other library, by copying it from the website and pasting to a file of your choosing.

**Comment by pr4deepr** [comment]
Thanks for that. 
Are you able to provide some data as well?  I couldn't find any except the text saying they have to contact you? 
It doesn't need to be uploaded here, but could be a link on Zenodo or something similar? 
You can then have the exact instructions for your toy dataset which will make it easy to test?

**Comment by nanthony21** [comment]
For now here is a download of the test data: https://drive.google.com/file/d/1La5Z84BEbAI_F6SRzBKr6Ly65Uqmpsrt/view?usp=sharing

Please extract it according to the readme here: https://github.com/BackmanLab/PWSpy/tree/master/tests/resources
Once the data is in place you should be able to run the tests using PyTest.

I will look into using Zenodo as a more permanent host for this data and will update the readme file when completed.

Just for clarification, are you in agreement that?:
 - The `examples.PWSImagePath` variable should be replaced by a variable in each example so that the examples can run independent of  how the Python working path is set up.
 - Documenting additional dependencies like `mpl_qt_viz` with inline comments in the examples is a suitable solution.

**Comment by pr4deepr** [comment]
Thanks for sharing that link. Is it possible to leave this link in the readme as well? 

> * The `examples.PWSImagePath` variable should be replaced by a variable in each example so that the examples can run independent of  how the Python working path is set up.

Yes!

> * Documenting additional dependencies like `mpl_qt_viz` with inline comments in the examples is a suitable solution.

If it isn't essential for running pwspy, then  have it as inline comments should work I think. It would be handy for users to try it on their own data anyway. So, can you also add this info to your[ examples page](https://pwspy.readthedocs.io/en/dev/examples.html) and to the [documentation link](https://github.com/BackmanLab/PWSpy#documentation) under your github readme, alongwith  instructions on how to install it, i.e., just conda and pip install commands should be enough.. 

Cheers
Pradeep

**Comment by nanthony21** [comment]
I believe all the suggestions here have been implemented in the most recent `master` branch. The test dataset is now available on Zenodo and is linked to from the readme.

**Comment by pr4deepr** [comment]
Thank you for being responsive.. 
Apologies, but I cannot find info on where the test dataset is. I do see changes in example code..

**Comment by pr4deepr** [comment]
Ahh, I just saw it here:
https://github.com/BackmanLab/PWSpy/tree/master/tests/resources

One more request would be to add it to the top of your page here:
https://pwspy.readthedocs.io/en/dev/examples.html

I think that will make it visible and easy to use.. Otherwise, it looks really good!

**Comment by nanthony21** [comment]
Thanks! Examples page has been updated.
