### ISSUE TITLE
automated testing

### ISSUE THREAD

**Issue by pr4deepr** [BackmanLab/PWSpy#19]
From my understanding, you have to run the testing locally after downloading all the data. 
Is it possible to use cropped images so automated testing can be done on github? This may not be within the immediate scope, but thought I'd ask.

**Comment by pr4deepr** [comment]
Also, as per the JOSS checklist: 

**Automated tests: Are there automated tests or` manual steps `described so that the functionality of the software can be verified?**

could you add a section in the readme elaborating on how to run the testing?

**Comment by nanthony21** [comment]
It would be definitely be possible to set up a CI/CD service to fetch test data and then run the tests. If there were more contributors I think this would be worthwhile but since I have so far been the sole contributor it just hasn't made sense to spend the time on it.

I will make sure to add a testing section to the top level readme.
